pagrindinis/app_blogas/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blogas'),
    path('<int:pk>', views.BlogDetailView.as_view(), name='blogai'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('myblog/', views.BlogsByUserListView.as_view(), name='my_blog'),
    path('myblog/new', views.BlogsByUserCreateView.as_view(), name='my_blog_new'),

]

pagrindinis/pagrindinis/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView


urlpatterns = [
    path('blog/', include('app_blogas.urls')),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='blog/', permanent=True)),
    path('tinymce/', include('tinymce.urls')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

pagrindinis/app_blogas/models.py
from django.db import models
from tinymce.models import HTMLField
from datetime import datetime

from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
import pytz
from tinymce.models import HTMLField

from PIL import Image


utc=pytz.UTC

# Create your models here.
class Field(models.Model):
    title=models.CharField('Pavadinimas',max_length=50,null=True)
    time=models.DateTimeField('Sukurta',null=True,auto_now=True)
    text=HTMLField('Tekstas',max_length=500,null=True)
    author=models.CharField(User,max_length=50,null=True)

    @property
    def cut_text(self):
        return self.text[:20]

    @property
    def comments_number(self):
        number=len(Comment.objects.filter(blog_id=self.pk))
        return number

    def __str__(self):
        return f"Pavadinimas: {self.title}/Laikas: {self.time}/Autorius: {self.author}"



class Comment(models.Model):
    blog_id=models.ForeignKey(Field,on_delete=models.SET_NULL,null=True,related_name='comment')
    email=models.EmailField('el.pastas',max_length=50,null=True,blank=True)
    time=models.DateTimeField('Sukurta',null=True, default=datetime.now)
    text=HTMLField('Komentaras',max_length=500,null=True)
    name=models.CharField('Vardas',max_length=50,null=True)

    def __str__(self):
        return f"Kas parase: {self.name}/Kada: {self.time}/Komentaras: {self.text}"


class Profile(models.Model):
    user= models.OneToOneField(User,on_delete=models.CASCADE)
    photo=models.ImageField(default="default.png",upload_to="profile_pics")

    def __str__(self):
        return f"{self.user.username} profilis"

    def save(self):
        super().save()
        img = Image.open(self.photo.path)
        if img.height > 200 or img.width > 200:
            output_size = (150, 150)
            img.thumbnail(output_size)
            img.save(self.photo.path)

pagrindinis/app_blogas/forms.py
from .models import Profile
from django import forms
from django.contrib.auth.models import User


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['photo']

pagrindinis/app_blogas/views.py
from django.shortcuts import render, get_object_or_404
from .models import Field
from django.views import generic
from django.core.paginator import Paginator
from django.db.models import Q

from django.shortcuts import redirect
from django.contrib.auth.forms import User
from django.views.decorators.csrf import csrf_protect
from django.contrib import messages

from django.contrib.auth.decorators import login_required
from .forms import UserUpdateForm, ProfileUpdateForm

from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.views.generic import ListView,CreateView,DeleteView,UpdateView


# Create your views here.
class BlogListView(generic.ListView):
     model = Field
     template_name = 'index.html'
     paginate_by = 3

class BlogDetailView(generic.DetailView):
     model = Field
     template_name = 'comment.html'


class BlogsByUserListView(LoginRequiredMixin, generic.ListView):
    model=Field
    template_name = 'user_blogs.html'
    paginate_by = 10

    def get_queryset(self):
        return Field.objects.filter(author=self.request.user)


class BlogsByUserCreateView(LoginRequiredMixin, CreateView):
    model = Field
    fields = ['title','text']
    success_url = "/blog/myblog/"
    template_name = 'user_blog_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)






@csrf_protect
def register(request):
    if request.method == "POST":
        # pasiimame reikšmes iš registracijos formos
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        # tikriname, ar sutampa slaptažodžiai
        if password == password2:
            # tikriname, ar neužimtas username
            if User.objects.filter(username=username).exists():
                messages.error(request, f'Vartotojo vardas {username} užimtas!')
                return redirect('register')
            else:
                # tikriname, ar nėra tokio pat email
                if User.objects.filter(email=email).exists():
                    messages.error(request, f'Vartotojas su el. paštu {email} jau užregistruotas!')
                    return redirect('register')
                else:
                    # jeigu viskas tvarkoje, sukuriame naują vartotoją
                    User.objects.create_user(username=username, email=email, password=password)
        else:
            messages.error(request, 'Slaptažodžiai nesutampa!')
            return redirect('register')
    return render(request, 'register.html')


#
@login_required
def profile(request):
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f"Profilis atnaujintas")
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,
    }
    return render(request, 'profile.html', context)

pagrindinis/app_blogas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Local Library</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Add additional CSS in static file -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
        <ul class="navbar-nav ml-auto">
            <li><a href="{% url 'blogas' %}">Pradžia</a></li>
              {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'profile' %}">
                  <svg class="bi bi-person" width="1.5em" height="1.5em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                    <path fill-rule="evenodd" d="M13 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM3.022 13h9.956a.274.274 0 00.014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 00.022.004zm9.974.056v-.002.002zM8 7a2 2 0 100-4 2 2 0 000 4zm3-2a3 3 0 11-6 0 3 3 0 016 0z" clip-rule="evenodd"/>
                  </svg>
                <li class="nav-item"><a class="nav-link" href="{% url 'my_blog_new'%}?next=/blog">Naujas B</a></li>
                {{ user.get_username }}</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'my_blog'%}">Mano</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'logout'%}">Atsijungti</a></li>
              {% else %}
                <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Prisijungti</a></li>
              {% endif %}
              {% if not user.is_authenticated %}
              <li class="nav-item"><a class="nav-link" href="{% url 'register'%}">Registruotis</a></li>
              {% endif %}
          </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">{% block content %}{% endblock %}</div>
    </div>
  </div>
</body>
</html>

pagrindinis/app_blogas/templates/comment.html
{% extends "base.html" %}

{% block content %}
    <h1>Pavadinimas: {{ field.title }}</h1>
    <h4>Autorius: {{ field.author }}</h4>
    <p>Sukurta: {{ field.time|date:"F d, Y H:i"}}</p>
    <h3>Tekstas: {{ field.text | safe }}</h3>
    <p>Komentarai: {{ field.comments_number }}</p>
        {% for comment in field.comment.all %}
            <li>{{ comment|safe }}</li>
        {% endfor %}
{% endblock %}

pagrindinis/app_blogas/templates/index.html
{% extends "base.html" %}

{% block content %}

    {% for field in field_list %}
    <h1>Pavadinimas: {{ field.title }}</h1>
    <h4>Autorius: {{ field.author }}</h4>
    <p>Sukurta: {{ field.time|date:"F d, Y H:i"}}</p>
    <h3>Tekstas: {{ field.cut_text | safe }}</h3>
    <p>Komentarai: {{ field.comments_number }}</p>
    <p><a href="{{ field.id }}">daugiau</a></p>
    </hr>
    {% endfor %}



    <div>
        {% if field_list.has_other_pages %}
                <ul>
                    {% for i in field_list.paginator.page_range %}
                        {% if field_list.number == i %}
                            <li>
                                <a href="">{{ i }}</a>
                            </li>
                        {% else %}
                            <li>
                                <a href="?page={{ i }}">{{ i }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                </ul>
        {% endif %}
    </div>
    <div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; pirmas</a>
            <a href="?page={{ page_obj.previous_page_number }}">atgal</a>
        {% endif %}

        <span class="current">
            {{ page_obj.number }} iš {{ page_obj.paginator.num_pages }}
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">pirmyn</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">paskutinis &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

pagrindinis/app_blogas/templates/profile.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-danger" role="alert">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
      <div class="media">
        <img class="rounded-circle account-img" src="{{ user.profile.photo.url }}">
        <div class="media-body">
          <h2 class="account-heading">{{ user.username }}</h2>
          <p class="text-secondary">{{ user.email }}</p>
        </div>
      </div>
       <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Profilio info</legend>
                {{ u_form|crispy }}
                {{ p_form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Atnaujinti</button>
            </div>
        </form>
    </div>
{% endblock content %}

pagrindinis/app_blogas/templates/register.html
{% extends "base.html" %}

{% block content %}

    <div class="container register">
        <h3>Registracija</h3><br/>
          {% if messages %}
            {% for message in messages %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Vartotojo vardas</label>
                <input name="username" type="text" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Iki 150 simbolių.</small>
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">El. paštas</label>
                <input name="email" type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">Nesidalinsime su niekuo, nesiųsime jokio spamo.
                    Reikalingas naujam slaptažodžiui išsiųsti. </small>
            </div>
            <div class="form-group">
                <label for="password">Slaptažodis</label>
                <input name="password" type="password" class="form-control" id="password" aria-describedby="pwdHelp">
                <small id="pwdHelp" class="form-text text-muted">Ne mažiau, kaip 8 simboliai. Negali būti vien tik
                    skaičiai</small>
            </div>
            <div class="form-group">
                <label for="password2">Pakartoti slaptažodį</label>
                <input name="password2" type="password" class="form-control" id="password2" aria-describedby="pwd2Help">
            </div>
            <button type="submit" class="btn btn-primary register-button">Registruotis</button>
        </form>
        <p>Jeigu užsiregistravote anksčiau, <a href="/login"><strong>prisijunkite.</strong></a></p>
    </div>

{% endblock %}

pagrindinis/app_blogas/templates/user_blog_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
    <form method="POST">
        {% csrf_token %}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Blogass</legend>
            {{ form|crispy }}
        </fieldset>
        <div class="form-group">
            <button class="btn btn-outline-info" type="submit">Išsaugoti</button>
        </div>
    </form>
    </div>
{% endblock content %}

pagrindinis/app_blogas/templates/user_blogs.html
{% extends "base.html" %}

{% block content %}
    <h1>Mano irasai</h1>

    {% if field_list %}
    <ul>
      {% for order in field_list %}
      <li>
        <a href="{% url 'blogai' order.pk %}">{{order.title}}</a> ({{ order.time }}) ({{ order.author }})
      </li>
      {% endfor %}
    </ul>
    {% else %}
      <p>There are no .</p>
    {% endif %}
{% endblock %}